### ISSUE TITLE
How to modify the right move greater than 127

### ISSUE THREAD

**Issue by zuozhehao** [T-vK/ESP32-BLE-Mouse#17]
How to modify the right move greater than 127.
I tried to modify `LOGICAL_MINIMUM(1), 0x81, ` but it didn't work.

**Comment by T-vK** [comment]
I don't think this is possible or would do what you think it does. This library is a drop-in replacement for the official USB Keyboard library btw. Since the problem you are having doesn't appear to be specific the Bluetooth functionality, I encourage you to look for existing answers on the Arduino forum.
